extends RigidBody3D
#REFERENCE TO MAIN MESH FOR THE OVERLAY
var overlayProperty = $
#ENTRIES PREFILLED MUST BE DEFINED OR OBJECT WILL NOT WORK
@export var itemStats = {
	"ItemName" : "",
	"ItemType" : "",
	#REMOVE COMMENT AND DEFINE ONLY IF ITEM IS FOOD OR DRINK
	#"Expires" : ,
	"InvIcon" : "",
	"Stackable": ,
	#USE AN RNG GENERATOR TO MAKE THIS, HIGHER NUMBER USUALLY THE BETTER
	"id":
}
#FOR CUSTOM FUNCTIONS, IF SCRAPS INTO AND AMOUNT IS NOT DEFINED WITH AN IN GAME MATERIAL, SCRAPPING OBJECT WILL NOT WORK
@export var itemProps = {
	#WEIGHT IS NECESSARY, EVEN IF 0
	"Weight" : ,
	#"Scraps into" : "",
	#"Amount" : 
	}

#MUST BE HERE EVEN IF IT DOES NOTHING WHEN YOU USE IT, IF IT DOES NOTHING, LEAVE IT AS PASS, IF IT DOES SOMETHING, MAKE IT TRIGGER A SEPARATE FUNCTION
func USE():
	pass
