extends RigidBody3D
#ENTRIES PREFILLED MUST BE DEFINED OR OBJECT WILL NOT WORK
@export var itemStats = {
	"ItemName" : "",
	"ItemType" : "",
	#REMOVE COMMENT AND DEFINE ONLY IF ITEM IS FOOD OR DRINK
	#"Expires" : ,
	"InvIcon" : "",
	"Weight" : ,
	"Stackable": ,
	#USE AN RNG GENERATOR TO MAKE THIS, HIGHER NUMBER USUALLY THE BETTER, MAX NUMBER OF 9223372036854775807
	#THAT NUMBER IS THE HIGHEST A 64 BIT INTEGER CAN BE, I HAVE NO IDEA WHAT WOULD HAPPEN IF YOU WENT OVER THAT
	"UUID":
}
#FOR CUSTOM FUNCTIONS, IF SCRAPS INTO AND AMOUNT IS NOT DEFINED WITH AN IN GAME MATERIAL, SCRAPPING OBJECT WILL NOT WORK
@export var itemProps = {
	#"Scraps into" : "",
	#"Amount" : 
	}
